language: node_js
node_js:
  - "4"
  - "6"

git:
  depth: 8

install:
  - npm install
  - npm run copy-env

script:
  - npm run build
  - npm test
  - npm run envjslint-ci

after_script:
  #- npm run envjs
  - ls -alh dist/

#End.
