language: node_js

node_js: 8

git:
  depth: 8

install: npm install

before_script: npm run copy-env

script:
  - npm run build
  - npm test
  - npm run envjslint-ci

after_script:
  #- npm run envjs
  - ls -alh dist/

# End.
