language: node_js
node_js:
  - "4"

git:
  depth: 5

install:
  #- npm install -g npm
  - npm install
  - npm run copy-env

script:
  - npm test
  - npm run jsonlint
  - npm run envjslint-ci

after_script:
  #- npm run envjs

#End.
