language: node_js
node_js:
  - "4"
  - "6"

git:
  depth: 8

install:
  - npm install
  - npm run copy-env

script:
  - npm test
  #- npm run jsonlint
  - npm run envjslint-ci

after_script:
  #- npm run envjs

#End.
